### ISSUE TITLE
ARMv8 Cryptography Extensions missing?

### ISSUE THREAD

**Issue by tarcieri** [rust-lang/stdarch#1003]
Not sure if this is related to #998 or not, but...

It looks like there have been [PRs to add the ARM cryptography extensions](https://github.com/rust-lang/stdarch/pull/929) but I don't see any of them listed here:

https://doc.rust-lang.org/core/arch/aarch64/index.html

@newpavlov suggested on a [recent rust-internals thread](https://internals.rust-lang.org/t/contributing-to-core-arch/14046) this might be a regression?

**Comment by bjorn3** [comment]
When https://github.com/rust-lang/stdarch/commit/9142a8a22d9ab4470167187e81aec503c2d70f60 added them for arm32, it accidentally also removed them from AArch64. Presumably the author was under the impression that all intrinsics for arm32 are re-exported for aarch64, which is not the case.

**Comment by tarcieri** [comment]
Per discussion on #929, it seems like this may be a dup of #1055
