### ISSUE TITLE
AArch64 SIMD store intrinsics missing

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/stdarch#1008]
For example, `vst1q_u64` is missing; this means it's not possible to effectively store a SIMD vector back to main memory...

**Comment by Amanieu** [comment]
A lot of the intrinsics are missing because nobody has gotten around to implementing them yet.

**Comment by raphaelcohn** [comment]
Fair enough...

**Comment by raphaelcohn** [comment]
Closing this as there are better issues to deal with this matter.
