### ISSUE TITLE
#![feature(stdsimd)] does not work in m1 mac pro

### ISSUE THREAD

**Issue by devillove084** [rust-lang/stdarch#1107]
When i use core::arch::aarch64 in my project. Vscode reminds me to add this feature in my project. But when i add this in my file. it does not work around. How can i do?

**Comment by bjorn3** [comment]
Did you add it to your lib.rs or main.rs? It needs to be added to the crate root. Not the current module.

**Comment by devillove084** [comment]
yes&nbsp; i add it in my main. rs,&nbsp; but it still failed.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 4, 2021 13:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rust-lang/stdarch] #![feature(stdsimd)] does not work in m1 mac pro (#1107)




 
Did you add it to your lib.rs or main.rs? It needs to be added to the crate root. Not the current module.
