### ISSUE TITLE
Incorrect naming of const generic in `_mm_extract_epi16()` et al

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/stdarch#1172]
The const generic naming in `_mm_extract_epi16()` is `IMM8`. Whilst this matches the Rust languages 'rules' for constants, the intention in the naming of these SIMD intrinsics was to match that of the vendors.

Consequently this const generic should be `imm8`.

Given that const generics are more akin to function parameters than constants, it's quite arguable if Rust language rules apply usefully in any event.

**Comment by Lokathor** [comment]
On the one hand, you're not wrong, on the other i can't imagine a reasonable person confusing the two (though i can imagine a simplistic search engine confusing the two maybe).

**Comment by raphaelcohn** [comment]
@Lokathor When writing, one tries to use a consistent style and naming to avoid forcing a casual reader to constantly have to be at the edge of focus, unable to simply parse and digest information (cf how we recognize words).

It's not only a search engine; it's anything that does simple text analysis. I've always encouraged my new devs to be as consistent as possible, because nothing beats search and replace without having to use regexes, or the ability to sort alphabetically. Another possibility is naive translation of, say, C code; I've done it by search and replace more than once over the years.

I'd argue for consistency, otherwise I'd find using SIMD intrinsics a lot easier if they didn't have such horrible abbreviated names and inconsistent function parameter types (sometimes a pointer to a vector, sometimes a pointer to an i32, using an i32 when it's really an u8, etc).

**Comment by Lokathor** [comment]
when translating C code, or otherwise reading code, the name of the argument on the declaration side doesn't really have anything to do with the name that the caller uses. Function callers can still name things `imm8` on their side if they wish.

i mean by using const generics at all we're already well outside of how C works, and you have to do some mental translation.

But I agree with you on the poorness of intel intrinsics. Allow me to plug the `safe_arch` crate if you want some better names.

**Comment by raphaelcohn** [comment]
1) the name of the argument on the translation side - true.

2) Exactly my point - mental translation of an insanely low-level detail.

Anyhow, this is rapidly getting into the weeds. Is this a change the Rust team are minded to make, or should I close this issue?

**Comment by Lokathor** [comment]
I don't speak for any teams or anyone, but since it has no practical effect on backwards compatibility or code generation a PR in this area might be accepted.

Wait for Amaneau to reply, they're the lead for this crate.

**Comment by Amanieu** [comment]
As @Lokathor said, there's no impact on backwards compatibility so I think changing the parameter names to lowercase is fine. I would be happy to accept a PR which does this.

**Comment by raphaelcohn** [comment]
@Amanieu that's great to know. However, I can't contribute PRs to Rust (and some other) projects at this time.
