### ISSUE TITLE
[std_detect] Atomic assumptions

### ISSUE THREAD

**Issue by MabezDev** [rust-lang/stdarch#1181]
This crate assumes that all targets building std, and therefore this crate support atomic operations because of the usage in the feature cache: https://github.com/rust-lang/stdarch/blob/master/crates/std_detect/src/detect/cache.rs#L8. The target this was spotted on was riscv32-imc (esp32c3) https://github.com/espressif/rust-esp32-example/issues/3.

**Comment by Amanieu** [comment]
The entire `std` crate assumes that `AtomicUsize` exists and supports all types of atomic operations (`compare_exchange`). If your target does not support atomic operations then you cannot use `std` and must use `core` and `alloc` instead.
