### ISSUE TITLE
Argument `imm8` of `_mm256_slli_epi32()` requires `const` only on nightly

### ISSUE THREAD

**Issue by rickyota** [rust-lang/stdarch#1188]
`imm8` of `_mm256_slli_epi32(a: __m256i, imm8: i32)` should not require `const` but somehow requires only on nightly.

This example raises an error on nightly since `imm8` is not a constant value.
`cargo +nightly run`

However, it does not raise any error on stable and `imm8` should not require `const`.
`cargo run`

Cargo versions are `cargo 1.53.0` and `cargo 1.55.0-nightly`

```
#[cfg(target_arch = "x86")]
use std::arch::x86::*;
#[cfg(target_arch = "x86_64")]
use std::arch::x86_64::*;
use std::convert::TryInto;

pub unsafe fn test1() {
    let ones_8 = _mm256_set1_epi8(1);
    let imm8 = 4;
    let a = _mm256_slli_epi32(ones_8, imm8);
    println!("a {:?}", a);
}
```

**Comment by bjorn3** [comment]
`imm` arguments should always be constants as they are directly encoded inside the instruction and not read from a register. That stable doesn't require it to be an imm was probably a bug. Doing so causes LLVM to generate very inefficient code to handle arbitrary values of the constant that is very likely not SIMD accelerated.

**Comment by rickyota** [comment]
Thank you! 

I didn't know that and I understand it, but it seems intel intrinsics guide does not require `imm` to be constant ([C++ compiler link](https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-intel-advanced-vector-extensions-2/intrinsics-for-logical-shift-operations/mm256-slli-epi16-32-64.html) ).
([intrinsics guide link](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm256_slli_epi32) is here but it is temporarily closed.)

Though, I see `imm` of `_mm256_slli_si256()` requires constant ([C++ compiler link](https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-intel-advanced-vector-extensions-2/intrinsics-for-logical-shift-operations/mm256-slli-si256.html)), so it seems odd...

**Comment by Lokathor** [comment]
In the first link it says

> count
> 8-bit immediate used for the operation

An immediate value must be a compile time constant. So the signature doesn't say `const`, but the other docs do indicate that.

**Comment by rickyota** [comment]
I see, thank you!
