### ISSUE TITLE
Miscompilation of `vbsl*_*` NEON intrinsics

### ISSUE THREAD

**Issue by l0calh05t** [rust-lang/stdarch#1191]
I tried this code:

```rust
#![feature(stdsimd)]

use std::arch::arm::*;
pub fn copysign(from: float32x4_t, to: float32x4_t) -> float32x4_t {
    unsafe {
        let mask = vdupq_n_u32(0x8000_0000);
        vbslq_f32(mask, from, to)
    }
}
```

using this Cargo configuration

```toml
[build]
target = "armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = ["-Ctarget-feature=+neon"]
```

I expected to see this happen: the generated code includes a `vbsl`/`vbit`/`vbif` instruction, i.e., like Clang's output for an equivalent C function
```asm
copysign(__simd128_float32_t, __simd128_float32_t):
        vmov.i32        q8, #0x80000000
        vbif    q0, q1, q8
        bx      lr
```

Instead, this happened: The function is optimized to returning `to`:

```asm
00000000 <neon_test::copysign>:
   0:   f4620acf        vld1.64 {d16-d17}, [r2]
   4:   f4400acf        vst1.64 {d16-d17}, [r0]
   8:   e12fff1e        bx      lr
```

We discussed this issue on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122652-new-members/topic/.E2.9C.94.20Possible.20miscompilation.20of.20NEON.20intrinsic.3F), and it appears that all NEON `vbsl*_*` intrinsics are implemented using `simd_select` which does lane selection instead of bitwise selection. The issue affects both `aarch64` and `armv7` targets.

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (1f0a591b3 2021-07-30)
binary: rustc
commit-hash: 1f0a591b3a5963a0ab11a35dc525ad9d46f612e4
commit-date: 2021-07-30
host: x86_64-pc-windows-msvc
release: 1.56.0-nightly
LLVM version: 12.0.1
```

<details><summary>Backtrace</summary>
<p>

```
PS D:\development\neon-test> $env:RUST_BACKTRACE="1"
PS D:\development\neon-test> cargo build --release
   Compiling neon-test v0.1.0 (D:\development\neon-test)
    Finished release [optimized] target(s) in 0.65s
```

</p>
</details>

**Comment by SparrowLii** [comment]
vbsl should be reimplemented. According to its implementation in [aarch64](https://godbolt.org/z/nnWf1cEfE) and [arm](https://godbolt.org/z/8Y3aKPsno) in clang, it should use functions such as `simd_and``simd_xor` instead of `simd_select`.( for arm, that is same as linking to llvm.arm.neon.vbsl)
[Here](https://rust.godbolt.org/z/sabfccfd1) is the result of copysign after it is reimplemented.

**Comment by l0calh05t** [comment]
I agree, but why the `xor` with `u32::MAX` instead of a `not` or following ARMs docs and using `operand1 EOR ((operand1 EOR operand4) AND operand3);`, which also optimized to the expected code when I used it as a workaround in my code?

**Comment by corecode** [comment]
What is the reason to implement the intrinsic via simd_* and not via a direct llvm intrinsic?  At least that's what I expected to happen.  With the current vbsl* implementation, my code runs ~11% slower compared to using vbsl (via inline assembler).

What code do I need to submit to fix this issue?

**Comment by SparrowLii** [comment]
Mainly is to be consistent with Clang's behavior, which is to take full advantage of llvm's automatic vector optimization. But if it is less efficient than using intrinsics directly, I think it's reasonable not to use such an implementation

**Comment by corecode** [comment]
Which one is preferred?  How can I make sure that the `assert_instr` tests actually run?

**Comment by Amanieu** [comment]
The priority here is to match Clang's behavior and generate the same LLVM IR. The `assert_instr` tests are mainly used as a sanity check, not a hard requirement. This is because the intrinsics don't actually guarantee any specific instruction, you have to use inline assembly if you depend on that.

**Comment by corecode** [comment]
I realized why the codegen checks did not fail:

The generated code contains the required instruction, but it also contains additional instructions that we don't want, because they change the semantics of the intrinsic:

```
0000000100086f2c <_stdarch_test_shim_vbslq_f32_bsl>:
100086f2c: 00 54 3f 4f  shl.4s  v0, v0, #31
100086f30: 00 a8 a0 4e  cmlt.4s v0, v0, #0
100086f34: 20 1c 62 6e  bsl.16b v0, v1, v2
100086f38: c0 03 5f d6  ret
```

Should we add a negative assertion option ("does not contain shl"), or should we just add a test for the correct behavior?

**Comment by corecode** [comment]
What do you think about writing the `vbsl*` intrinsics this way:

``` rust
pub unsafe fn vbsl_s8(a: uint8x8_t, b: int8x8_t, c: int8x8_t) -> int8x8_t {
    let not = int8x8_t(-1, -1, -1, -1, -1, -1, -1, -1);
    transmute(simd_or(
        simd_and(a, transmute(b)),
        simd_and(simd_xor(a, transmute(not)), transmute(c)),
    ))
}
```

This matches the clang [codegen](https://github.com/llvm/llvm-project/blob/main/clang/lib/CodeGen/CGBuiltin.cpp#L10838).

Currently the unit tests only use `::MAX` and `::MIN` for the mask and therefore do not distinguish between a lane select bit and a true bit select.  How should we change the tests?  Using some other integers that do or do not have the lane select bit set do reveal the current bug, but look a bit ad-hoc:

``` rust
    #[simd_test(enable = "neon")]
    unsafe fn test_vbsl_s16() {
        let a = u16x4::new(u16::MAX, 0, 1, 2);
        let b = i16x4::new(i16::MAX, i16::MAX, i16::MAX, i16::MAX);
        let c = i16x4::new(i16::MIN, i16::MIN, i16::MIN, i16::MIN);
        let e = i16x4::new(i16::MAX, i16::MIN, i16::MIN | 1, i16::MIN | 2);
        let r: i16x4 = transmute(vbsl_s16(transmute(a), transmute(b), transmute(c)));
        assert_eq!(r, e);
    }
```

Testing float bit selects seems difficult in any case.

**Comment by Amanieu** [comment]
Looks good!

For the instruction test you can disable it by setting the instruction to `nop`. I think it's more hassle than it's worth in this case.
