### ISSUE TITLE
_mm_store_ps may be broken

### ISSUE THREAD

**Issue by SparrowLii** [rust-lang/stdarch#1225]
I tried the following code:

    use std::arch::x86_64::*;
    use std::intrinsics::transmute;
    
    fn main() {
        let mut arr = [0f32; 100];
        let ptr = arr.as_mut_ptr();
        unsafe {
            for i in 0..100 / 4 {
                let offset = i * 4;
                let off = offset as f32;
                let t = _mm_setr_ps(off, off + 1., off + 2., off + 3.);
                _mm_store_ps(ptr.add(offset), t);
                //_mm_storeu_si128(ptr.add(offset).cast(), transmute(t));
            }
        }
        for i in 0..100 {
            assert_eq!(arr[i], i as f32);
        }
    }

The program cannot be executed [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a6a6677750b7df2f0f7cac4ef16e479c)
But if we use `_mm_storeu_si128`, the program can be executed normally [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d9b2778397ffdc985cdd206f1130c4de)

**Comment by Lokathor** [comment]
Nothing about this example ensures that the array is aligned to 16, which is a requirement for `_mm_store_ps`.

`_mm_storeu_si128`, as well as `_mm_storeu_ps` and `_mm_storeu_pd`, do not have alignment requirements.

If you change your first example to `_mm_storeu_ps` instead of `_mm_store_ps` (note the extra "U" in there), then it will work.

**Comment by SparrowLii** [comment]
> If you change your first example to _mm_storeu_ps instead of _mm_store_ps (note the extra "U" in there), then it will work.

Thanks! I did not notice the aligned requirement. I did not notice the aligned requirement. If this is its original purpose, it means there is no problem. I think this issue can be closed

**Comment by Lokathor** [comment]
Yeah, standard load/store require the location to be aligned to the size of the entire SIMD type, not just the element type. The Load/Store Unaligned lets you ignore that requirement as a few cycle speed penalty.
