### ISSUE TITLE
_mm256_cmplt_epi8 missing

### ISSUE THREAD

**Issue by kazuk** [rust-lang/stdarch#1226]
_mm256_cmplt_epi* is not provided, is there any reason?

_mm256_cmpgt_eip8 is existing in code.

https://github.com/rust-lang/stdarch/blob/master/crates/core_arch/src/x86/avx2.rs#L726

I looked at the code for _mm256_cmpgt_epi*. I didn't find it difficult to implement _mm256_cmplt_epi*.

If there's no particular reason why _mm256_cmplt_epi* isn't provided and it's just not working, I'd love to help.

**Comment by hkratz** [comment]
stdarch only has the official x86 intrinsics, as specified by Intel and implemented in GCC or clang ([Intel reference](https://software.intel.com/sites/landingpage/IntrinsicsGuide/)). `_mm256_cmplt_epi8` is not listed in the reference. Where did you see it?

It is also not needed as you can substitute `_mm256_cmplt_epi8(a, b)` with `_mm256_cmpgt_epi8(b, a)`.

**Comment by kazuk** [comment]
Oh, sorry, I check reference.

I found `_mm256_cmplt_epi8_mask` in avx512bw/vl. I think I made a mistake when I saw this.

Thanks.
