### ISSUE TITLE
Why is `F16C` still unstable?

### ISSUE THREAD

**Issue by Razordor** [rust-lang/stdarch#1234]
I noticed that most `x86_64` intrinsics were stable, yet `F16C` isn't. I'd like to know what is keeping it from hitting stable, and what can be done to make it stable. According to another [tracking issue comment](https://github.com/rust-lang/rust/issues/48556#issuecomment-743190548) there doesn't seem to be anything blocking it.

**Comment by Amanieu** [comment]
There is no specific reason, just that nobody has pushed for its stabilization yet. In this case all that would be needed is a PR to add stability attributes to these function to stabilize them.

**Comment by aloucks** [comment]
It's odd that the runtime check seems to think it was stablized in `1.27.0`:
https://github.com/rust-lang/stdarch/blob/91c64cd2a0a4ff02ad2db2ebac74fa50f206fa16/crates/std_detect/src/detect/arch/x86.rs#L166

It looks like this was missed:
https://github.com/rust-lang/rust/blob/887999d163bace7e79370b952bdd1f930ff4cdd5/compiler/rustc_feature/src/active.rs#L241

Does it just need to be moved here?:
https://github.com/rust-lang/rust/blob/887999d163bace7e79370b952bdd1f930ff4cdd5/compiler/rustc_feature/src/accepted.rs

**Comment by Amanieu** [comment]
The feature detection was stabilized separately from the intrinsics.

**Comment by Amanieu** [comment]
The F16C intrinsics aren't stable yet, this is still waiting on FCP in #1366.
