### ISSUE TITLE
Implement `in` and `out` intrinsics for x86/x86_64

### ISSUE THREAD

**Issue by seritools** [rust-lang/stdarch#1244]
For kernel/driver-level code it'd be nice to easily have access to the I/O port commands [`in`](https://c9x.me/x86/html/file_module_x86_id_139.html) and [`out`](https://c9x.me/x86/html/file_module_x86_id_222.html).

**Comment by bjorn3** [comment]
I don't think the intel intrinsic guide has any intrinsics for them. We have chosen to not invent our own intrinsics but instead copy the vendor C intrinsics. You can use the x86_64 crate instead. https://docs.rs/x86_64/0.14.6/x86_64/instructions/port/index.html

**Comment by seritools** [comment]
Ohh, that makes sense, thanks :)
