### ISSUE TITLE
Dependency on an external git repository

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/stdarch#1255]
This repository, which is part of the Rust project, [now](https://github.com/rust-lang/stdarch/commits/master/.gitmodules) depends on a git repository which is not part of the Rust project through a submodule. This means the Rust project is now dependent on the correct management of that 3rd party of their repo (such as that the commits are indefinitely maintained in one of the branches) or the Rust project will fail to build. It's not clear to me that this implication was considered during the merge of #1237

**Comment by Amanieu** [comment]
This submodule is only used by a test tool in stdarch's CI. If this is still a concern, we could just take the csv from that submodule and included directly in the repo.

**Comment by CatsAreFluffy** [comment]
The submodule was removed in #1427, so I think this can be closed now.
