### ISSUE TITLE
The __rdtscp intrinsic should return the value in the IA32_TSC_AUX MSR

### ISSUE THREAD

**Issue by iankronquist** [rust-lang/stdarch#1282]
The [x86 rdtscp instruction](https://www.felixcloutier.com/x86/rdtscp) puts the value of the current time step counter into eax:edx and the value of the IA32_TSC_AUX msr into ecx. However, the [rust __rdtscp intrinsic](https://doc.rust-lang.org/core/arch/x86/fn.__rdtscp.html) does not return the value of IA32_TSC_AUX. The value of IA32_TSC_AUX is useful for a variety of reasons, but most notably it's the easiest way to get the current core id from userland. Getting this information atomically in one instruction can be useful for implementing certain types of fair locks too.

Rust should give us all of the information returned by the rdtscp instruction.

**Comment by bjorn3** [comment]
The function accepts a pointer to which the aux value is written to. This should match the C intrinsic.

**Comment by iankronquist** [comment]
My mistake, I should have filed this bug against the x86 crate which does not propagate the value.

If you're curious:
https://docs.rs/x86/latest/x86/time/fn.rdtscp.html
