### ISSUE TITLE
Compile error on RISC-V due to .insn (llvm<=13 only)

### ISSUE THREAD

**Issue by XieJiSS** [rust-lang/stdarch#1291]
I'd like to create this issue to track the status of compiling `.insn i 0x0F, 0, x0, x0, 0x010` directives, as well as `pause` / `fence w,0` (these three are aliases)

Currently with clang 13.0.1, this error occurs when compiling rust:

```
error: unknown directive
   |
note: instantiated into assembly here
  --> <inline asm>:1:2
   |
1  |     .insn i 0x0F, 0, x0, x0, 0x010
   |     ^

error: could not compile `log` due to previous error
```

This is introduced by https://github.com/rust-lang/stdarch/commit/597b8e89a08d26d320615df663e5cbab0800566d. I'm not saying that the commit itself has issues: rust can use this safely because `rust-lang/llvm-project` has cherry-picked the upstream commit to support `.insn`: https://github.com/rust-lang/rust/pull/91528. However, for those using clang v13.0.1 (or, let's say, the unmodified llvm toolchain), they may encounter this issue during compiling. Hence, I create this issue as a explanation as well as tracking the status of llvm support for `.insn`.

The code should compile fine with clang 14.

**Comment by Amanieu** [comment]
In general the functions in `std::arch` are only fully supported when using Rust's custom LLVM fork. Normally this isn't a problem unless you specifically use these intrinsics in user code.

However in this case I would accept a PR to change this to a `.word` or equivalent since this is preventing Rust itself from compiling.

**Comment by luojia65** [comment]
The mainstream LLVM has released LLVM 14: https://github.com/llvm/llvm-project/releases/tag/llvmorg-14.0.0 .

**Comment by XieJiSS** [comment]
Thanks, I'm closing this issue as LLVM 14 can compile rust now
