### ISSUE TITLE
Reserve API for future dynamic sized std::simd

### ISSUE THREAD

**Issue by luojia65** [rust-lang/stdarch#1300]
Lots of processors would provide fixed size SIMD instructions on hardware, but ARM SVE and RISC-V V provides dynamic sized ones. It's dynamic for what vector width the actual architecture implementation would choose.

By now if we don't know how to implement this in Rust frontend, we can reserve API for it. I suggest we can consider probable dynamic sized SIMD when we design API in `std::simd` before stabilization, for example the `Simd` structure and `as_simd` function.

I'll list one possible design of dynamic sized SIMD as follows, after discussed with Rustcc community members.

## One possible design

To implement it in Rust, it may be applicable to apply `#[repr(simd)]` for structure that wraps `[u8]`, `[i64]` or `[usize]` etc. types after changes to rustc compiler. This structure would directly be stored, loaded from vector registers (it fit into one register if no register grouping).

The dynamic sized type would typically include data and its length. We store data into one vector register. If we need its length, architecture specific registers like `vl` for RISC-V should be read, we don't need to store length information elsewhere.

LLVM has vscale parameter for such dynamic sized SIMD. For example if type `isize` is represented as LLVM IR type `i64`, type `#[repr(simd)] struct MySimd([isize])` would be represented like `<vscale x 1 x i64>` in LLVM IR. And further arithmetic operations would be implemented into intrinsic functions that operates on such types.

This design still have one unsolved problem, it's mostly about how the dynamic structure would save on program stack. This problem exists when we need to use dynamic Simd on non-leaf functions in call graph.

**Comment by luojia65** [comment]
@bjorn3 Thanks for reply! I may post this on forum to discuss on how this part would be processed, I may submit an RFC before any changes.

**Comment by Amanieu** [comment]
This should probably be discussed on the internals forum as a pre-RFC to discuss potential designs to address this. Once a more complete design is ready, a RFC can be written up.
