### ISSUE TITLE
RP2040 CPU target with ArmV6m but also Thumb2

### ISSUE THREAD

**Issue by kpishere** [rust-lang/stdarch#1312]
How do I enable generation of thumb2 code for CPU RP2040? This is Coretex-M0+ with Tumb 2 support.

A target of "thumbv6m-none-eabi" only supports regular thumb code assembly.

ref: https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf

I get errors like .. 

```
error: instruction requires: thumb2
   |
note: instantiated into assembly here
  --> <inline asm>:40:1
   |
40 | str sp, [r1, #-8]!```

**Comment by bjorn3** [comment]
You can use `-Ctarget-features=+thumb2` to enable thumb2 usage. Note however that the Cortex-M0+ only supports some thumb2 instructions, so it will likely crash due to LLVM trying to use unsupported thumb2 instructions. In other words I don't think you can safely use thumb2 on Cortex-M0+ with LLVM.

**Comment by Amanieu** [comment]
The Cortex-M0+ does *not* support Thumb2. It only supports a small subset of Thumb2 (7 instructions) as part of ARMv6-M. Only ARMv7-M CPUs support the full Thumb2 instruction set.

**Comment by Lokathor** [comment]
For this particular situation, you could *maybe* just build.rs a separate assembly file and link it in. Smuggle it past rustc that way without disrupting all the rust code.

if that makes sense with however you're using that inline asm.
