### ISSUE TITLE
Typo in llvm intrinsic names?

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/stdarch#1361]
I found several llvm intrinsics ending with `.6i8` rather than `.v16i8` in the AArch64 code. Is this a typo? For example https://github.com/rust-lang/stdarch/blob/dc632d1f8a683a53d2f86e2fb2f8387b97d0c69c/crates/core_arch/src/aarch64/neon/mod.rs#L165

**Comment by Amanieu** [comment]
It is a typo, but it seems like LLVM silently fixes it up: https://rust.godbolt.org/z/1aoYzejGj
