### ISSUE TITLE
Potentially ambiguous glob re-exports in `core_arch/src/arm/mod.rs`

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/stdarch#1381]
Hi, I was working on <https://github.com/rust-lang/rust/pull/107880>, and came across

https://github.com/rust-lang/stdarch/blob/7fbf6975e7d324e17fb680358d7c1b0f34c19c95/crates/core_arch/src/arm/mod.rs#L73-L81

I think this is a case of potentially ambiguous glob re-exports because functions under `arm_shared::neon` is re-exported alongside `neon`. If a downstream user (or in docs) tries to use a function that is present in both `neon` and `arm_shared` namespaces then an error will occur (provided target feature v7 or doc is enabled).

E.g. the WIP error message reveals a potential ambiguous function `vcvtq_u32_f32`:

```rust
error[E0252]: the name `vcvtq_u32_f32` is defined multiple times
  --> /checkout/library/core/src/../../stdarch/crates/core_arch/src/arm/mod.rs:81:9
   |
73 | pub use crate::core_arch::arm_shared::*;
   |         -------------------------------
   |         |
   |         previous import of the value `vcvtq_u32_f32` here
   |         you can use `as` to change the binding name of the import
...
81 | pub use neon::*;
   |         ^^^^^^^ `vcvtq_u32_f32` reimported here
   |
   = note: `vcvtq_u32_f32` must be defined only once in the value namespace of this module
```

If it is intended that `vcvtq_u32_f32` from `neon` should override the re-export from the glob re-export of `arm_shared::*`, then I think it needs to be specified by name, i.e.

```rust
pub use crate::core_arch::arm_shared::*;
pub use neon::vcvtq_u32_f32;
```

In this case, `vcvtq_u32_f32` will override the function of the same name from `arm_shared::*` because it is named and not a glob re-export.

**Comment by Amanieu** [comment]
This is accidental, there definitely shouldn't be any overlap between `arm`/`aarch64` and `arm_shared`. It's a good thing your lint catches this!

Is `vcvtq_u32_f32` the only function that triggers this or are there also others?

**Comment by jieyouxu** [comment]
> This is accidental, there definitely shouldn't be any overlap between `arm`/`aarch64` and `arm_shared`. It's a good thing your lint catches this!
> 
> Is `vcvtq_u32_f32` the only function that triggers this or are there also others?

I'm still working on the lint, I think there could be a couple more functions. Currently the lint is just a hard error because I was still trying to combat false positives :3

**Comment by jieyouxu** [comment]
Sorry about this, I think it is a false positive because https://github.com/rust-lang/rust/pull/107880#issuecomment-1435971507 (TL;DR: the one in `arm` shadows the one in `arm_shared`).
