### ISSUE TITLE
Status of AVX-512DQ

### ISSUE THREAD

**Issue by mert-kurttutan** [rust-lang/stdarch#1437]
Hi,
What is the status of the implementation of AVX-512DQ (needed 512 wide binary ops, e.g. and_ps) ?
I noticed this draft that was started 2 years ago.
https://github.com/rust-lang/stdarch/pull/954

If there is anything I could do,  I want to help.

**Comment by Amanieu** [comment]
I believe #954 is the only PR working towards support for AVX-512DQ, but it seems abandoned.

@vertexclique Are you still working on this? If not then @mert-kurttutan feel free to take over that PR by importing it into your fork.

**Comment by vertexclique** [comment]
I have no time to work, I can mentor the person who can take over this.

**Comment by sayantn** [comment]
@vertexclique I can implement AVX512DQ if you want. I would need some guidance from you.

**Comment by vertexclique** [comment]
For sure, I am on discord and zulip.

**Comment by Amanieu** [comment]
Now implemented by #1581.
