### ISSUE TITLE
arm intrinsic vst1q_s64_x4 dosent show up in the documentation

### ISSUE THREAD

**Issue by psvri** [rust-lang/stdarch#1444]
Hello,

I see that the arm intrinsic vst1q_s64_x4 dosent show up in the std docs as see in this link https://doc.rust-lang.org/core/arch/aarch64/fn.vst1q_s64_x4.html .

vst1q_s64_x4 is a valid intrinsic fn already implemented in the rust compiler which can be proved via this godbolt (https://godbolt.org/z/77P1hcMjT)

**Comment by Lokathor** [comment]
The ARM functions are not yet completely added. A PR would be appreciated if you could implement any missing intrinsic functions.

**Comment by psvri** [comment]
@Lokathor the intrinsic is implemented but its not showing up in the rust std documentation.

**Comment by Lokathor** [comment]
ah, i understand now

**Comment by Amanieu** [comment]
Fixed by  #1445.
