### ISSUE TITLE
ambiguous glob re-exports caused by `vcvtq_s32_f32`

### ISSUE THREAD

**Issue by bvanjoi** [rust-lang/stdarch#1446]
There are two `vcvtq_s32_f32` functions defined in `core_arch::arm::neon` and `core_arch::arm_shared::neno::generated` and they are re-exported at the following locations:

- [pub use crate::core_arch::arm_shared::*](https://github.com/rust-lang/stdarch/blob/master/crates/core_arch/src/arm/mod.rs#L59C1-L59C41) 
- [pub use neon::*](https://github.com/rust-lang/stdarch/blob/master/crates/core_arch/src/arm/mod.rs#L67)

This issue was found at https://github.com/rust-lang/rust/pull/113099#issuecomment-1652234540

**Comment by bvanjoi** [comment]
`ambiguous-glob-reexports` is currently set as a warning level lint. The error due to the `#![deny(warnings)]` attribute, maybe we can easily solve this problem by add `#![allow(ambiguous_glob_reexports)]`

**Comment by lu-zero** [comment]
why is it happening only for `vcvtq_s32_f32` ? or it is just the first of many?

**Comment by bvanjoi** [comment]
only for `vcvtq_s32_f32` and  `vcvtq_u32_f32`.

**Comment by lu-zero** [comment]
the `neon.rs` has `use crate::core_arch::arm_shared::neon::*;`

the hand crafted impl could be removed.
