### ISSUE TITLE
stabilize has_cpuid

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/stdarch#573]
The `has_cpuid` functionality is tricky, and cannot be implemented in stable Rust because of the amount of inline assembly required.

@alexcrichton I'd like to propose that functionality for stabilization, should I just send a PR here and do an FCP ?

**Comment by alexcrichton** [comment]
@gnzlbg yeah I think it's fine to send a PR here and we can tag in libs folks to do an FCP. We'd want to be sure to cc relevant folks who may have thoughts as well. It'd also be great to write up some notes on the PR about why it's being stabilized as well as prior art (like in Clang) just for reference!

**Comment by gnzlbg** [comment]
This was found "not useful", so it is not in the path towards stabilization anymore.
