### ISSUE TITLE
Don't use i128 to represent WebAssembly vectors

### ISSUE THREAD

**Issue by tlively** [rust-lang/stdarch#577]
`i128` and `<1 x i128>` aren't natively supported types in the WebAssembly LLVM backend, even with SIMD enabled, so any LLVM IR containing them will lower to suboptimal wasm code that passes the them around in linear memory rather than on the stack or in locals. I'm experimenting with a fix for this, but it is rather brittle and we probably won't want to land it, so it would be much better to make this change on the Rust side. Valid llvm types are `<16 x i8>`, `<8 x i16>`, `<4 x i32>`, `<2 x i64>`, `<4 x f32>`, and `<2 x f64>`.

**Comment by alexcrichton** [comment]
👍 we can definitely make this change, was just an internal detail!

**Comment by gnzlbg** [comment]
I'll send a PR changing this to use `<4 x i32>`, as @alexcrichton mentions, this is an internal implementation detail and changing it should have no effect.
