### ISSUE TITLE
Missing x86/_64 MMX functions

### ISSUE THREAD

**Issue by TheDan64** [rust-lang/stdarch#579]
It seems like `_mm_empty`, `_mm_madd_pi16`, `_mm_xor_si64` and a handful of other simd functions don't exist, neither in stable nor behind the stdsimd feature. In fact, it seems like the remaining TODO list in #40 is unimplemented.

I was just wondering if there is any technical reason for these missing functions, or have they just not been implemented yet?

Thanks!

**Comment by alexcrichton** [comment]
Ah if these are missing it's just by mistake! Then can be added at any time :)

**Comment by TheDan64** [comment]
Ah, that's good to know! So most of the functions that I've found to be missing seem to be in the aforementioned TODO list under MMX & SSE. I've also found these two which aren't listed there: [_mm_cvtph_ps](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_cvtph_ps&expand=5236) & [_mm_mulhrs_pi16](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_mulhrs_pi16&expand=5236,3954) but can be found in the standard C SIMD headers

**Comment by alexcrichton** [comment]
Ah so we haven't actually stabilized (or pursued too aggressively) the MMX-related intrinsics as they have weird ABI issues in LLVM and don't seem to be too widely used in the wild (those intrinsics with `__m64`), but we can always add them as unstable at least!

**Comment by workingjubilee** [comment]
Direct MMX support is no longer in scope for `std::arch`, see:
- https://github.com/rust-lang/stdarch/pull/890
