### ISSUE TITLE
Incorrect CPUID feature name in the Intrinsics Guide: FP16C instead of F16C

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/stdarch#738]
The Intel Intrinsics Guide for the 16-bit half-precision float intrinsics calls the CPUID feature flag "FP16C", see: https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=Other&text=fp16&expand=1711

LLVM (e.g. ), CPUID Wikipedia page (https://en.wikipedia.org/wiki/CPUID), and thIntel® 64 and IA-32 Architectures Software Developer’s Manual Volume 2 (2A, 2B, 2C & 2D): Instruction Set Reference, A-Z (https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf) all call this feature "F16C" instead. 

This is probably a bug in the Intrinsics Guide that we should report and track.

**Comment by sayantn** [comment]
Intel has fixed this bug (this is not in version 3.6.8 anymore)
