### ISSUE TITLE
NEON/AdvSIMD comparison intrinsics

### ISSUE THREAD

**Issue by myfreeweb** [rust-lang/stdarch#754]
… are not *LLVM* intrinsics, they're represented in IR as `icmp` and literally written as just `<` in C:

```c
// arm_neon.h
#ifdef __LITTLE_ENDIAN__
__ai uint32x4_t vcltq_u32(uint32x4_t __p0, uint32x4_t __p1) {
  uint32x4_t __ret;
  __ret = (uint32x4_t)(__p0 < __p1);
  return __ret;
// ...
```

```c
  uint32x4_t a, b, c = vcltq_u32(a, b);
```

```llvm
  %cmp.i = icmp ult <4 x i32> %2, %3
  %sext.i = sext <4 x i1> %cmp.i to <4 x i32>
```

```asm
  cmhi   v0.4s, v1.4s, v0.4s
```

Is it possible to emit this w/o inline assembly right now? I don't see a comparison implementation for these types…

cc #148

**Comment by myfreeweb** [comment]
ah, `simd_lt` works. I guess I should implement these missing intrinsics using these `simd_llvm` things to make it public API.

**Comment by gnzlbg** [comment]
Yeah, check out the `llvm` module for the current "generic" `simd_` intrinsics that are available. There might be a couple more that are not used in `stdsimd` yet, so if you need anything that's not there, let us know here.

**Comment by sunnygleason** [comment]
FWIW, if you like the 1:1 correspondence with intrinsic names, I think a bunch of these intrinsics (and more) are implemented in https://github.com/rust-lang/stdarch/pull/792 ... See https://github.com/rust-lang/stdarch/pull/792/files#diff-66d90852ae58a548e0a34d1cb5e481ecR881

Maybe your :+1: could help it get merged... :)

**Comment by myfreeweb** [comment]
@sunnygleason amazing work, I'll look into it later
