### ISSUE TITLE
Mismatch issue number for stdsimd

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/stdarch#780]
In rust-lang/rust repo, `48556` is used as an unstable `stdsimd`'s issue number. But in this repository, `27731` is used instead. ~~This difference causes a tidy error on my local.~~ (Tidy errors are unrelated.) Which is correct?

**Comment by gnzlbg** [comment]
The two issues are different, and feature gate different things. Both are correct. See the corresponding issues in the rust-lang/rust issue tracker, for what they feature gate.

**Comment by JohnTitor** [comment]
Oh, I didn't know that. Thanks!
