### ISSUE TITLE
_mm_movemask_epi8 test result is a palindrome

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/stdarch#785]
https://github.com/rust-lang/stdarch/blob/65c9fa511acb1841bac37f92ad9b586ca45f1df7/crates/core_arch/src/x86/sse2.rs#L4162

This means that reversing result order wont cause the test to fail. I noticed this, because the test succeeded despite the order being wrong when emulating it in https://github.com/bjorn3/rustc_codegen_cranelift.

**Comment by gnzlbg** [comment]
I'm not sure what you are suggesting. That we add another run-time test ?

**Comment by bjorn3** [comment]
Yes, or adapt it a bit, so that it isn't a palindrome anymore.
