### ISSUE TITLE
change in the code generation of _mm_broadcastq_epi64

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/stdarch#791]
The update of LLVM9 potentially changed the generated code of `_mm_broadcastq_epi64` from using `vbroadcastq` as expected to using `vmovddup`. We should investigate whether this new instruction is more efficient, and if so, then we can close this issue. Otherwise, we should fill an LLVM. 

From the failed test:

```
disassembly for stdarch_test_shim__mm_broadcastq_epi64_vpbroadcastq: 
	 0: pushq %rbp
	 1: movq %rsp, %rbp
	 2: leaq 0xb8394(%rip), %rax
	 3: leaq 0x1108ae(%rip), %rcx
	 4: movq %rax, (%rcx)
	 5: vmovddup %xmm0, %xmm0
	 6: popq %rbp
	 7: retq
	 8: nopl (%rax,%rax)
thread 'core_arch::x86::avx2::assert__mm_broadcastq_epi64_vpbroadcastq' panicked at 'failed to find instruction `vpbroadcastq` in the disassembly'
```

cc @nikic

**Comment by alexcrichton** [comment]
[According to godbolt](https://godbolt.org/z/QNSdCB) Rust/Clang are still producing the same codegen, which looks like LLVM just switched to picking a presumably faster instruction for this.

**Comment by gnzlbg** [comment]
Yes, the question is whether these are faster instructions or whether LLVM had a regression. Clang does not test the assembly of all their intrinsics, so sometimes regressions do happen :/

**Comment by mati865** [comment]
It was intentional change: https://reviews.llvm.org/D57519

**Comment by gnzlbg** [comment]
Thanks for finding that! This case is covered in their tests there, so I'm closing this as "the new behavior is ok".

**Comment by mati865** [comment]
Literally first result for searching `vpbroadcastq vmovddup` in Google but you're welcome.
