### ISSUE TITLE
Add an env override to std_detect

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/stdarch#804]
Sometimes it can be useful to disable certain extensions even if the host cpu sports them.

- [x] Refactor the cached check logic in `src/detect/mod.rs`
- [ ] Add a `RUST_STD_DETECT_DISABLE` `env::var` check
  - Takes a space separate list of strings
  - For each of them mapping to an arch Feature, turn it off.
- [ ] Document its existence

@gnzlbg Do you see any problem in this approach?

**Comment by gnzlbg** [comment]
Shall this env variable be read at run-time, or at build time ?

Either way, I think enabling this should be put behind a cargo feature that's disabled by default.

**Comment by bjorn3** [comment]
I think it should be during runtime, so you dont have to recompile the world.

**Comment by lu-zero** [comment]
> Shall this env variable be read at run-time, or at build time ?

run-time

> Either way, I think enabling this should be put behind a cargo feature that's disabled by default.

Not sure how to name the feature. (and how to advertise it)

**Comment by bjorn3** [comment]
> Not sure how to name the feature. (and how to advertise it)

`allow-runtime-detect-override`?

**Comment by lu-zero** [comment]
I'm sold on it, now, which crate should expose it?

**Comment by lu-zero** [comment]
Also: should we make the cpu feature checks macro behave like log?

**Comment by gnzlbg** [comment]
> I'm sold on it, now, which crate should expose it?

Maybe `std_detect` ? 

> Also: should we make the cpu feature checks macro behave like log?

There is an RFC that allows something like that: https://github.com/rust-lang/rfcs/pull/2725 but I'm not sure if that's what you mean.

**Comment by lu-zero** [comment]
It is exactly what I meant.
Also this use-case might be mentioned [here](https://github.com/gnzlbg/rfcs/blob/target_feature_runtime/text/0000-target-feature-runtime.md#the-target_feature_detection_runtime-attribute)

I'll start sending the refactoring patches and the initial impl soon.

**Comment by lu-zero** [comment]
I started with https://github.com/rust-lang/stdarch/pull/806

Where should I put the documentation about the env variable?

Can I use [this](https://crates.io/crates/arg_enum_proc_macro) to implement the mapping `name -> feature` mapping?
