### ISSUE TITLE
Stabilize cmpxchg16b

### ISSUE THREAD

**Issue by sfackler** [rust-lang/stdarch#827]
Is anything holding up stabilization of double-wide CAS? It doesn't seem so from some searching.

**Comment by gnzlbg** [comment]
Weird, I thought I saw a stabilization PR for this one somewhere.

**Comment by thomcc** [comment]
Is there some story here? I've always assumed that it was intentionally left unstabilized in order to avoid stabilizing 128 bit atomics in some form prior to `Atomic[UI]128`.

However, with asm! stabilization on the way, this ship will sail, so I don't a reason not to.

**Comment by Amanieu** [comment]
I'm happy to accept a PR for stabilizing it. I only have one minor nit about the implementation: the `ud2` should be changed to a normal panic.
