### ISSUE TITLE
`stdimd_internal` or `stdsimd_internal` ?

### ISSUE THREAD

**Issue by haraldh** [rust-lang/stdarch#841]
I stumbled upon `stdimd_internal`. Is this a typo or be purpose?

`#[unstable(feature = "stdimd_internal", issue = "0")]`

**Comment by Amanieu** [comment]
This is a typo.

**Comment by workingjubilee** [comment]
Ah, I knew I forgot something with my PR. This is fixed.

**Comment by haraldh** [comment]
https://github.com/rust-lang/stdarch/blob/7895ab191867be7612aaaaeeea1b982749826504/crates/core_arch/src/x86/mod.rs#L437

**Comment by workingjubilee** [comment]
Ah, I missed a spot. Good job, me.
