### ISSUE TITLE
x86 Various issues with extract_epiNN functions

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/stdarch#867]
## 1. Inconsistent function signatures

The SSE versions have the following signatures:
```rust
pub unsafe fn _mm_extract_epi8(a: __m128i, imm8: i32) -> i32;
pub unsafe fn _mm_extract_epi16(a: __m128i, imm8: i32) -> i32;
```
But the AVX versions have the following:
```rust
pub unsafe fn _mm256_extract_epi8(a: __m256i, imm8: i32) -> i8;
pub unsafe fn _mm256_extract_epi16(a: __m256i, imm8: i32) -> i16;
```
Note the difference in return type. Since [Intel specifies](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=extract_epi) these all return `int`, it's not clear how this happened. I thought the function signatures are supposed to be machine-checked?

## 2. Incorrect sign extension

```rust
use core::arch::x86_64::*;

fn main() {
    println!("{:x}", unsafe{_mm_extract_epi16(_mm_set1_epi8(!0), 0)});
}
```

This prints: `ffffffff`. [Intel specifies](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_extract_epi16&expand=2426,2426) the upper 16 bits should be 0.

cc @AdrianCX

**Comment by Amanieu** [comment]
The second one is definitely a bug which should be fixed.

For the first one, apparently our intrinsics data has the return type as int8/int16:
```
<intrinsic tech='AVX2' sequence='true' rettype='__int8' name='_mm256_extract_epi8'>
	<type>Integer</type>
	<CPUID>AVX2</CPUID>
	<category>Swizzle</category>
	<parameter varname='a' type='__m256i'/>
	<parameter varname="index" type='const int'/>
	<description>Extract an 8-bit integer from "a", selected with "index", and store the result in "dst".</description>
	<operation>
dst[7:0] := (a[255:0] &gt;&gt; (index * 8))[7:0]
	</operation>
	<header>immintrin.h</header>
</intrinsic>
```

**Comment by jethrogb** [comment]
Looks like https://github.com/rust-lang/stdarch/blob/master/crates/stdarch-verify/x86-intel.xml is out of date. That one's from 09/07/2017 but the [most recent one](https://software.intel.com/sites/landingpage/IntrinsicsGuide/files/data-3.5.2.xml) is from 06/05/2020.

**Comment by jethrogb** [comment]
Please re-open the issue (due to #878)
