### ISSUE TITLE
Are there special steps to build?

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/stdarch#875]
I wanted to add some ARM intrinsics and so I forked the repo, cloned the fork to my rpi4 (an ARM device), and then ran `cargo test` just to make sure everything is fine to start.

To my great surprise, it couldn't even build the tests. There's an error log [here](https://gist.github.com/rust-play/2de78d84c2e0ba79543f49d1ad2b64ae), and the TLDR of it is that a macro expected the `TARGET` environment variable to be set and a bunch of types are missing. I ran it again:
* `TARGET=armv7-unknown-linux-gnueabihf cargo test`

And it still has all the errors about types being missing. I'm completely baffled as to what's going on, and the CI file doesn't seem to show any other special steps, so I'm at a loss.

**Comment by Amanieu** [comment]
What error messages do you get after setting TARGET? The tests in this repo are really only intended to be run by CI or via Docker.

**Comment by Lokathor** [comment]
As shown in the error log, cargo thought that most all of the SIMD types were missing somehow.

If `cargo test` doesn't work for this crate, do we just add some stuff and submit a PR and let the CI be the test run?

**Comment by Amanieu** [comment]
You can use `ci/run-docker.sh armv7-unknown-linux-gnueabihf` which is what CI runs.

**Comment by Amanieu** [comment]
Actually I figured out what was missing. You need to use this command:
```
RUSTFLAGS="-C target-feature=+neon" TARGET=armv7-unknown-linux-gnueabihf ci/run.sh armv7-unknown-linux-gnueabihf
```

RUSTFLAGS is set in the CI config `.github/workflows/main.yml`.

**Comment by Lokathor** [comment]
I will try try this later today after work and report back.

**Comment by Lokathor** [comment]
Ah! I forgot to say that it did work.
