### ISSUE TITLE
Migration from llvm_asm! to asm!

### ISSUE THREAD

**Issue by tesuji** [rust-lang/stdarch#904]
Not really a high priority task, but it would be nice to see official rust crates
using new recommended language features over old ones.

Related issues/PRs:
* #846
* https://github.com/rust-lang/rust/issues/72016

**Comment by bjorn3** [comment]
This would be nice for cg_clif as only `asm!` is implemented.

**Comment by lzutao** [comment]
As noted in https://github.com/rust-lang/rust/pull/76669#issuecomment-691849014 , we have a restrictions 
that we have to support LLVM 8 (which is currently the minimum supported version). 
We have to use ATT syntax for x86.

**Comment by lzutao** [comment]
Note: Some architectures currently aren't supported by `asm!`: mips, ppc, ...
So if the llvm_asm code don't have target_arch or target_arch only on those archs,
we have to continue using llvm_asm.

**Comment by josephlr** [comment]
It looks like all of the current `llvm_asm!` uses in `core_arch` and `std_detect` are on `arm`, `aarch64`, `x86`, or `x86_64`, so we should be able to switch all of them to `asm!`, using att-syntax on 32-bit x86.

The only other use [is in `assert-instr-macro`](https://github.com/rust-lang/stdarch/blob/bf687fa6aeffe01742b2e807b3b47d17eba1ce1e/crates/assert-instr-macro/src/lib.rs#L148), where it's not used for assembly, but as a "volatile" fence. This is similar to how [libcore implements `black_box`](https://github.com/rust-lang/rust/blob/56293097f7f877f1350a6cd00f79d03132f16515/library/core/src/hint.rs#L126). So perhaps we can just use that instead.
