### ISSUE TITLE
Do we need polynomial scalar types for Arm NEON?

### ISSUE THREAD

**Issue by AdamHillier** [rust-lang/stdarch#940]
For the Arm NEON polynomial vector types, stdarch currently uses a struct of unsigned integers, e.g.: https://github.com/rust-lang/stdarch/blob/dd981c00dca35127a4307046d025ab2259d492b9/crates/core_arch/src/arm/neon/mod.rs#L17-L18

However, there is no dedicated polynomial scalar type. `arm_neon.h` defines some polynomial scalar types such as `poly8_t` and `poly16_t`, which are then used as arguments or return types for some NEON intrinsics, e.g. [`vld1_lane_p8`](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics?search=vld1_lane_p8), [`vld1_dup_p16`](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics?search=vld1_dup_p16), [`vdup_n_p8`](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics?search=vdup_n_p8), [`vget_lane_p16`](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics?search=vget_lane_p16).

Clang typedefs`poly8_t`/`poly16_t` to `uint8_t`/`uint16_t` on Aarch64 and `int8_t`/`int16_t` otherwise (see [here](https://github.com/llvm/llvm-project/blob/f507aa17b791af3028d321ccfb83c5bfaf315f02/clang/utils/TableGen/NeonEmitter.cpp#L2339-L2349)).

I have a local branch where I've added all of the `vld1_dup_${type}` intrinsics, and used `u8`/`u16` instead of the polynomial scalar types where necessary. However, the `stdarch-verify` tests then fail because they complain that the type signature doesn't match the one given in the Arm documentation (which uses `poly8_t`/`poly16_t`). So, for now, not having polynomial scalar types blocks full implementation of all Neon intrinsics (unless the signature verification tests are modified).

**Comment by Amanieu** [comment]
I think it's fine to add those typedefs and make them match the definitions in Clang.

**Comment by AdamHillier** [comment]
> I think it's fine to add those typedefs and make them match the definitions in Clang.

I think I agree. It's then a little bit weird because you'd be able to perform integer arithmetic with a polynomial scalar type, which doesn't make much sense, but I guess that's something to worry about when it comes to stabilisation (assuming it is a concern).

**Comment by Amanieu** [comment]
In `stdarch` we just try to copy the vendor C APIs as much as possible without overthinking it. Rust-friendly wrappers can be provided by crates if that is desired.

**Comment by AdamHillier** [comment]
Closed by #941.
