### ISSUE TITLE
Could not find specification for target "x86_x64-unknown-linux-gnu"

### ISSUE THREAD

**Issue by kangshan1157** [rust-lang/stdarch#987]
I installed rust through "curl https://sh.rustup.rs -sSf | sh" and the rust has been successfully installed.
Then I ran the following commands:
1) rustup default nightly
2) git clone https://github.com/rust-lang/stdarch
3) cd stdarch
4) TARGET=x86_x64-unknown-linux-gnu ci/run.sh
Then the following error occured:
...
cargo test --target=x86_x64-unknown-linux-gnu --manifest-path=crates/core_arch/Cargo.toml --release --
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target x86_x64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: Error loading target specification: Could not find specification for target "x86_x64-unknown-linux-gnu". Use `--print target-list` for a list of built-in targets

My OS is CentOS 8 Stream and PC is Cascade Lake.

**Comment by bjorn3** [comment]
> x86_**x**64-unknown-linux-gnu

It must be x86_64, not x86_x64.

**Comment by kangshan1157** [comment]
I copied the command from "https://github.com/rust-lang/stdarch/blob/master/CONTRIBUTING.md". Yes, change to "TARGET=x86_64-unknown-linux-gnu", the code can be compiled and run. 
@bjorn3 Thanks a lot.
